{{- if and (not .Values.api.existingSecret) .Values.api.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refmd.fullname" . }}-api
  labels:
    {{- include "refmd.componentLabels" (dict "component" "api" "context" .) | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
