{{- if and .Values.mcpServer.enabled (not .Values.mcpServer.existingSecret) .Values.mcpServer.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refmd.fullname" . }}-mcp-server
  labels:
    {{- include "refmd.componentLabels" (dict "component" "mcp-server" "context" .) | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.mcpServer.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}

