{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "refmd.fullname" . }}-minio
  labels:
    {{- include "refmd.componentLabels" (dict "component" "minio" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "refmd.componentLabels" (dict "component" "minio" "context" .) | nindent 4 }}
{{- end }}
