{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "refmd.fullname" . }}-postgres
  labels:
    {{- include "refmd.componentLabels" (dict "component" "postgres" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "refmd.componentLabels" (dict "component" "postgres" "context" .) | nindent 4 }}
{{- end }}
